import '../models/models.dart';

final medications = {
  'aspirin': Medication(
    name: 'Aspirin',
    activeIngredient: 'Acetylsalicylic Acid',
    usedFor: ['Pain relief', 'Fever reduction', 'Blood clot prevention'],
    whenToUse: ['For mild to moderate pain', 'For fever', 'Heart attack prevention'],
    contraindications: ['Aspirin allergy', 'Bleeding disorders', 'Active ulcers', 'Pregnancy (3rd trimester)'],
    dosage: '500mg every 4-6 hours, max 4000mg daily',
    sideEffects: ['Stomach upset', 'Heartburn', 'Easy bruising', 'Rash'],
    simpleExplanation: 'Aspirin is a common pain reliever and fever reducer. It also helps prevent blood clots.',
  ),

  'paracetamol': Medication(
    name: 'Paracetamol (Acetaminophen)',
    activeIngredient: 'Paracetamol',
    usedFor: ['Pain relief', 'Fever reduction'],
    whenToUse: ['For mild to moderate pain', 'For fever', 'As aspirin alternative'],
    contraindications: ['Liver disease', 'Alcohol dependence', 'Paracetamol allergy'],
    dosage: '500-1000mg every 4-6 hours, max 4000mg daily',
    sideEffects: ['Generally well-tolerated', 'Rare allergic reactions', 'Liver damage at overdose'],
    simpleExplanation: 'Paracetamol is a gentle pain reliever and fever reducer. Gentler on stomach than aspirin.',
  ),

  'amoxicillin': Medication(
    name: 'Amoxicillin',
    activeIngredient: 'Amoxicillin Trihydrate',
    usedFor: ['Bacterial infections', 'Ear infections', 'Throat infections', 'UTIs'],
    whenToUse: ['Only when prescribed', 'For confirmed bacterial infections', 'Take full course'],
    contraindications: ['Penicillin allergy', 'Cephalosporin allergy', 'Mononucleosis'],
    dosage: '250-500mg three times daily for 7-10 days',
    sideEffects: ['Nausea', 'Diarrhea', 'Allergic rash', 'Yeast infection'],
    simpleExplanation: 'Amoxicillin is an antibiotic that kills harmful bacteria. Complete the full course.',
    requiresPrescription: true,
  ),

  'ibuprofen': Medication(
    name: 'Ibuprofen',
    activeIngredient: 'Ibuprofen',
    usedFor: ['Pain relief', 'Fever reduction', 'Inflammation', 'Arthritis symptoms'],
    whenToUse: ['For headaches', 'For muscle aches', 'For arthritis', 'Under supervision for long-term'],
    contraindications: ['NSAID allergy', 'Pregnancy (3rd trimester)', 'Active ulcers', 'Severe kidney/liver disease'],
    dosage: '200-400mg every 4-6 hours, max 1200mg daily (OTC)',
    sideEffects: ['Stomach upset', 'Heartburn', 'Nausea', 'Dizziness', 'Rare serious GI bleeding'],
    simpleExplanation: 'Ibuprofen reduces pain and inflammation. Take with food to avoid stomach upset.',
  ),

  'metformin': Medication(
    name: 'Metformin',
    activeIngredient: 'Metformin Hydrochloride',
    usedFor: ['Type 2 diabetes', 'Blood sugar control', 'Prediabetes'],
    whenToUse: ['As prescribed for diabetes', 'With meals to reduce GI upset', 'Regularly for best effect'],
    contraindications: ['Severe kidney disease', 'Liver disease', 'Heart failure', 'Acute illness'],
    dosage: 'Usually 500-1000mg twice daily with meals',
    sideEffects: ['Nausea', 'Stomach pain', 'Metallic taste', 'Diarrhea', 'Vitamin B12 deficiency'],
    simpleExplanation: 'Metformin helps control blood sugar in diabetes. Take with meals and as prescribed.',
    requiresPrescription: true,
  ),

  'lisinopril': Medication(
    name: 'Lisinopril',
    activeIngredient: 'Lisinopril Dihydrate',
    usedFor: ['High blood pressure', 'Heart failure', 'Heart attack prevention'],
    whenToUse: ['Daily as prescribed', 'Same time each day', 'Long-term management'],
    contraindications: ['ACE inhibitor allergy', 'Angioedema history', 'Pregnancy', 'Severe kidney disease'],
    dosage: 'Usually 10mg once daily',
    sideEffects: ['Dry cough', 'Dizziness', 'Fatigue', 'Hyperkalemia', 'Rare angioedema'],
    simpleExplanation: 'Lisinopril lowers blood pressure and protects the heart. Take at same time daily.',
    requiresPrescription: true,
  ),

  'atorvastatin': Medication(
    name: 'Atorvastatin',
    activeIngredient: 'Atorvastatin Calcium',
    usedFor: ['High cholesterol', 'Heart disease prevention', 'Stroke prevention'],
    whenToUse: ['Daily as prescribed', 'Usually in evening', 'Long-term use'],
    contraindications: ['Statin allergy', 'Active liver disease', 'Pregnancy', 'Breastfeeding'],
    dosage: 'Usually 10-80mg once daily',
    sideEffects: ['Muscle pain', 'Fatigue', 'Nausea', 'Liver enzyme elevation', 'Rare muscle breakdown'],
    simpleExplanation: 'Atorvastatin lowers cholesterol and reduces heart disease risk. Take daily.',
    requiresPrescription: true,
  ),

  'omeprazole': Medication(
    name: 'Omeprazole',
    activeIngredient: 'Omeprazole Magnesium',
    usedFor: ['Heartburn', 'GERD', 'Ulcer treatment', 'Ulcer prevention'],
    whenToUse: ['Once daily for heartburn', 'Before meals', '14-day course for OTC use'],
    contraindications: ['Omeprazole allergy', 'Certain drug interactions', 'Vitamin B12 deficiency'],
    dosage: '20mg once daily, can increase to 40mg',
    sideEffects: ['Headache', 'Diarrhea', 'Nausea', 'Vitamin B12 deficiency', 'Bone fractures (long-term)'],
    simpleExplanation: 'Omeprazole reduces stomach acid and treats heartburn. Take before meals.',
  ),

  'levothyroxine': Medication(
    name: 'Levothyroxine',
    activeIngredient: 'Levothyroxine Sodium',
    usedFor: ['Hypothyroidism', 'Thyroid hormone replacement', 'Thyroid cancer prevention'],
    whenToUse: ['Once daily on empty stomach', 'Same time each day', 'Lifelong use usually needed'],
    contraindications: ['Uncontrolled hyperthyroidism', 'Untreated adrenal deficiency', 'Recent MI'],
    dosage: 'Usually 25-200 mcg daily, adjusted based on TSH levels',
    sideEffects: ['Tremor', 'Anxiety', 'Insomnia', 'Weight loss', 'Palpitations if overdosed'],
    simpleExplanation: 'Levothyroxine replaces thyroid hormone. Take on empty stomach for best absorption.',
    requiresPrescription: true,
  ),

  'metoprolol': Medication(
    name: 'Metoprolol',
    activeIngredient: 'Metoprolol Tartrate',
    usedFor: ['High blood pressure', 'Angina', 'Heart attack', 'Arrhythmias'],
    whenToUse: ['Daily as prescribed', 'With or without food', 'Regular dosing important'],
    contraindications: ['Beta-blocker allergy', 'Severe bradycardia', 'Heart block', 'Uncontrolled asthma'],
    dosage: 'Usually 50-200mg daily in divided doses',
    sideEffects: ['Fatigue', 'Dizziness', 'Slow heart rate', 'Sexual dysfunction', 'Sleep issues'],
    simpleExplanation: 'Metoprolol slows heart rate and lowers blood pressure. Take as prescribed.',
    requiresPrescription: true,
  ),

  'sertraline': Medication(
    name: 'Sertraline',
    activeIngredient: 'Sertraline Hydrochloride',
    usedFor: ['Depression', 'Anxiety', 'OCD', 'PTSD', 'Panic disorder'],
    whenToUse: ['Once daily', 'With or without food', 'Takes 2-4 weeks for full effect'],
    contraindications: ['SSRI allergy', 'MAOI use', 'Uncontrolled narrow-angle glaucoma'],
    dosage: 'Usually 50mg daily, range 50-200mg',
    sideEffects: ['Nausea', 'Insomnia', 'Sexual dysfunction', 'Headache', 'Withdrawal if stopped abruptly'],
    simpleExplanation: 'Sertraline helps depression and anxiety. Takes time to work - be patient.',
    requiresPrescription: true,
  ),

  'doxycycline': Medication(
    name: 'Doxycycline',
    activeIngredient: 'Doxycycline Hyclate',
    usedFor: ['Bacterial infections', 'Acne', 'Malaria prevention', 'Lyme disease'],
    whenToUse: ['As prescribed', 'Take with full glass of water', 'Avoid lying down for 30 minutes'],
    contraindications: ['Tetracycline allergy', 'Pregnancy', 'Children under 8 years', 'Severe liver disease'],
    dosage: '100mg once or twice daily',
    sideEffects: ['Nausea', 'Photosensitivity', 'Yeast infection', 'Esophageal irritation', 'Rare severe reactions'],
    simpleExplanation: 'Doxycycline is an antibiotic. Take with water and avoid lying down.',
    requiresPrescription: true,
  ),

  'loratadine': Medication(
    name: 'Loratadine',
    activeIngredient: 'Loratadine',
    usedFor: ['Allergies', 'Itching', 'Hives', 'Allergic rhinitis'],
    whenToUse: ['Once daily', 'With or without food', 'Best taken at same time'],
    contraindications: ['Loratadine allergy', 'Severe liver disease', 'Kidney disease'],
    dosage: '10mg once daily',
    sideEffects: ['Headache', 'Dry mouth', 'Fatigue', 'Nausea', 'Generally well-tolerated'],
    simpleExplanation: 'Loratadine treats allergies and itching. Non-drowsy antihistamine.',
  ),

  'cetirizine': Medication(
    name: 'Cetirizine',
    activeIngredient: 'Cetirizine Hydrochloride',
    usedFor: ['Allergies', 'Hives', 'Itching', 'Allergic reactions'],
    whenToUse: ['Once daily', 'With or without food', 'Can take in morning or evening'],
    contraindications: ['Cetirizine allergy', 'Severe kidney disease'],
    dosage: '10mg once daily',
    sideEffects: ['Drowsiness (more than loratadine)', 'Headache', 'Dry mouth', 'Fatigue'],
    simpleExplanation: 'Cetirizine relieves allergies and itching. May cause drowsiness.',
  ),

  'ranitidine': Medication(
    name: 'Ranitidine',
    activeIngredient: 'Ranitidine Hydrochloride',
    usedFor: ['Heartburn', 'GERD', 'Ulcer treatment', 'Stomach acid reduction'],
    whenToUse: ['As directed', 'With or without food', 'Can take before meals or bedtime'],
    contraindications: ['Ranitidine allergy', 'Severe kidney disease', 'Porphyria'],
    dosage: '150mg twice daily or 300mg at bedtime',
    sideEffects: ['Headache', 'Constipation', 'Diarrhea', 'Nausea', 'Rare serious reactions'],
    simpleExplanation: 'Ranitidine reduces stomach acid and treats heartburn. Take as directed.',
  ),

  'fluticasone': Medication(
    name: 'Fluticasone Nasal Spray',
    activeIngredient: 'Fluticasone Propionate',
    usedFor: ['Nasal allergies', 'Allergic rhinitis', 'Nasal polyps', 'Sinus inflammation'],
    whenToUse: ['Once or twice daily', 'In each nostril', 'Regular use for best effect'],
    contraindications: ['Fluticasone allergy', 'Untreated infections', 'Recent nasal surgery'],
    dosage: '1-2 sprays each nostril once or twice daily',
    sideEffects: ['Nasal irritation', 'Epistaxis', 'Sore throat', 'Headache', 'Generally well-tolerated'],
    simpleExplanation: 'Fluticasone spray reduces nasal inflammation from allergies. Use regularly.',
  ),

  'gabapentin': Medication(
    name: 'Gabapentin',
    activeIngredient: 'Gabapentin',
    usedFor: ['Nerve pain', 'Seizures', 'Hot flashes', 'Restless leg syndrome'],
    whenToUse: ['As prescribed', 'Multiple times daily', 'Take with or without food'],
    contraindications: ['Gabapentin allergy', 'Abrupt discontinuation'],
    dosage: 'Usually 300-600mg three times daily',
    sideEffects: ['Dizziness', 'Fatigue', 'Blurred vision', 'Weight gain', 'Mood changes'],
    simpleExplanation: 'Gabapentin helps nerve pain and seizures. Can take with food.',
    requiresPrescription: true,
  ),

  'simvastatin': Medication(
    name: 'Simvastatin',
    activeIngredient: 'Simvastatin',
    usedFor: ['High cholesterol', 'Heart disease prevention', 'Cardiovascular protection'],
    whenToUse: ['Once daily in evening', 'With or without food', 'Regular use important'],
    contraindications: ['Statin allergy', 'Active liver disease', 'Pregnancy', 'Breastfeeding'],
    dosage: 'Usually 10-80mg once daily',
    sideEffects: ['Muscle pain', 'Fatigue', 'Headache', 'Nausea', 'Liver enzyme elevation'],
    simpleExplanation: 'Simvastatin lowers cholesterol and heart disease risk. Take in evening.',
    requiresPrescription: true,
  ),

  'prednisone': Medication(
    name: 'Prednisone',
    activeIngredient: 'Prednisone',
    usedFor: ['Inflammation', 'Allergic reactions', 'Autoimmune diseases', 'Asthma'],
    whenToUse: ['As prescribed', 'With food if needed', 'Follow exact dosing schedule'],
    contraindications: ['Prednisone allergy', 'Systemic fungal infections', 'Vaccinia', 'Varicella'],
    dosage: 'Varies widely from 5mg to 60mg daily',
    sideEffects: ['Increased appetite', 'Sleep problems', 'Mood changes', 'Bone loss', 'Infection risk'],
    simpleExplanation: 'Prednisone reduces inflammation and immune responses. Follow dosing carefully.',
    requiresPrescription: true,
  ),

  'fluoxetine': Medication(
    name: 'Fluoxetine',
    activeIngredient: 'Fluoxetine Hydrochloride',
    usedFor: ['Depression', 'Anxiety', 'OCD', 'Bulimia', 'PMDD'],
    whenToUse: ['Once daily', 'With or without food', 'Takes 2-4 weeks for full effect'],
    contraindications: ['SSRI allergy', 'MAOI use', 'Uncontrolled glaucoma'],
    dosage: 'Usually 20mg daily, range 20-80mg',
    sideEffects: ['Nausea', 'Insomnia', 'Sexual dysfunction', 'Headache', 'Withdrawal effects'],
    simpleExplanation: 'Fluoxetine treats depression and anxiety. Takes time to work fully.',
    requiresPrescription: true,
  ),

  'cimetidine': Medication(
    name: 'Cimetidine',
    activeIngredient: 'Cimetidine',
    usedFor: ['Heartburn', 'GERD', 'Ulcers', 'Acid reflux'],
    whenToUse: ['As needed for heartburn', 'With meals and at bedtime', 'Standard OTC dosing'],
    contraindications: ['Cimetidine allergy', 'Severe kidney/liver disease'],
    dosage: '200mg with meals and at bedtime, up to 400mg at bedtime',
    sideEffects: ['Headache', 'Constipation', 'Diarrhea', 'Nausea', 'Rare interactions'],
    simpleExplanation: 'Cimetidine reduces stomach acid and treats heartburn. Take as directed.',
  ),
};
