import '../models/models.dart';

final medications = {
  'aspirin': Medication(
    name: 'Aspirin',
    activeIngredient: 'Acetylsalicylic Acid',
    usedFor: ['Pain relief', 'Fever reduction', 'Blood clot prevention'],
    whenToUse: ['For mild to moderate pain', 'For fever', 'Heart attack prevention'],
    contraindications: ['Aspirin allergy', 'Bleeding disorders', 'Active ulcers', 'Pregnancy (3rd trimester)'],
    dosage: '500mg every 4-6 hours, max 4000mg daily',
    sideEffects: ['Stomach upset', 'Heartburn', 'Easy bruising', 'Rash'],
    simpleExplanation: 'Aspirin is a common pain reliever and fever reducer. It also helps prevent blood clots.',
  ),

  'paracetamol': Medication(
    name: 'Paracetamol (Acetaminophen)',
    activeIngredient: 'Paracetamol',
    usedFor: ['Pain relief', 'Fever reduction'],
    whenToUse: ['For mild to moderate pain', 'For fever', 'As aspirin alternative'],
    contraindications: ['Liver disease', 'Alcohol dependence', 'Paracetamol allergy'],
    dosage: '500-1000mg every 4-6 hours, max 4000mg daily',
    sideEffects: ['Generally well-tolerated', 'Rare allergic reactions', 'Liver damage at overdose'],
    simpleExplanation: 'Paracetamol is a gentle pain reliever and fever reducer. Gentler on stomach than aspirin.',
  ),

  'amoxicillin': Medication(
    name: 'Amoxicillin',
    activeIngredient: 'Amoxicillin Trihydrate',
    usedFor: ['Bacterial infections', 'Ear infections', 'Throat infections', 'UTIs'],
    whenToUse: ['Only when prescribed', 'For confirmed bacterial infections', 'Take full course'],
    contraindications: ['Penicillin allergy', 'Cephalosporin allergy', 'Mononucleosis'],
    dosage: '250-500mg three times daily for 7-10 days',
    sideEffects: ['Nausea', 'Diarrhea', 'Allergic rash', 'Yeast infection'],
    simpleExplanation: 'Amoxicillin is an antibiotic that kills harmful bacteria. Complete the full course.',
    requiresPrescription: true,
  ),

  'ibuprofen': Medication(
    name: 'Ibuprofen',
    activeIngredient: 'Ibuprofen',
    usedFor: ['Pain relief', 'Fever reduction', 'Inflammation', 'Arthritis symptoms'],
    whenToUse: ['For headaches', 'For muscle aches', 'For arthritis', 'Under supervision for long-term'],
    contraindications: ['NSAID allergy', 'Pregnancy (3rd trimester)', 'Active ulcers', 'Severe kidney/liver disease'],
    dosage: '200-400mg every 4-6 hours, max 1200mg daily (OTC)',
    sideEffects: ['Stomach upset', 'Heartburn', 'Nausea', 'Dizziness', 'Rare serious GI bleeding'],
    simpleExplanation: 'Ibuprofen reduces pain and inflammation. Take with food to avoid stomach upset.',
  ),

  'metformin': Medication(
    name: 'Metformin',
    activeIngredient: 'Metformin Hydrochloride',
    usedFor: ['Type 2 diabetes', 'Blood sugar control', 'Prediabetes'],
    whenToUse: ['As prescribed for diabetes', 'With meals to reduce GI upset', 'Regularly for best effect'],
    contraindications: ['Severe kidney disease', 'Liver disease', 'Heart failure', 'Acute illness'],
    dosage: 'Usually 500-1000mg twice daily with meals',
    sideEffects: ['Nausea', 'Stomach pain', 'Metallic taste', 'Diarrhea', 'Vitamin B12 deficiency'],
    simpleExplanation: 'Metformin helps control blood sugar in diabetes. Take with meals and as prescribed.',
    requiresPrescription: true,
  ),

  'lisinopril': Medication(
    name: 'Lisinopril',
    activeIngredient: 'Lisinopril Dihydrate',
    usedFor: ['High blood pressure', 'Heart failure', 'Heart attack prevention'],
    whenToUse: ['Daily as prescribed', 'Same time each day', 'Long-term management'],
    contraindications: ['ACE inhibitor allergy', 'Angioedema history', 'Pregnancy', 'Severe kidney disease'],
    dosage: 'Usually 10mg once daily',
    sideEffects: ['Dry cough', 'Dizziness', 'Fatigue', 'Hyperkalemia', 'Rare angioedema'],
    simpleExplanation: 'Lisinopril lowers blood pressure and protects the heart. Take at same time daily.',
    requiresPrescription: true,
  ),

  'atorvastatin': Medication(
    name: 'Atorvastatin',
    activeIngredient: 'Atorvastatin Calcium',
    usedFor: ['High cholesterol', 'Heart disease prevention', 'Stroke prevention'],
    whenToUse: ['Daily as prescribed', 'Usually in evening', 'Long-term use'],
    contraindications: ['Statin allergy', 'Active liver disease', 'Pregnancy', 'Breastfeeding'],
    dosage: 'Usually 10-80mg once daily',
    sideEffects: ['Muscle pain', 'Fatigue', 'Nausea', 'Liver enzyme elevation', 'Rare muscle breakdown'],
    simpleExplanation: 'Atorvastatin lowers cholesterol and reduces heart disease risk. Take daily.',
    requiresPrescription: true,
  ),

  'omeprazole': Medication(
    name: 'Omeprazole',
    activeIngredient: 'Omeprazole Magnesium',
    usedFor: ['Heartburn', 'GERD', 'Ulcer treatment', 'Ulcer prevention'],
    whenToUse: ['Once daily for heartburn', 'Before meals', '14-day course for OTC use'],
    contraindications: ['Omeprazole allergy', 'Certain drug interactions', 'Vitamin B12 deficiency'],
    dosage: '20mg once daily, can increase to 40mg',
    sideEffects: ['Headache', 'Diarrhea', 'Nausea', 'Vitamin B12 deficiency', 'Bone fractures (long-term)'],
    simpleExplanation: 'Omeprazole reduces stomach acid and treats heartburn. Take before meals.',
  ),

  'levothyroxine': Medication(
    name: 'Levothyroxine',
    activeIngredient: 'Levothyroxine Sodium',
    usedFor: ['Hypothyroidism', 'Thyroid hormone replacement', 'Thyroid cancer prevention'],
    whenToUse: ['Once daily on empty stomach', 'Same time each day', 'Lifelong use usually needed'],
    contraindications: ['Uncontrolled hyperthyroidism', 'Untreated adrenal deficiency', 'Recent MI'],
    dosage: 'Usually 25-200 mcg daily, adjusted based on TSH levels',
    sideEffects: ['Tremor', 'Anxiety', 'Insomnia', 'Weight loss', 'Palpitations if overdosed'],
    simpleExplanation: 'Levothyroxine replaces thyroid hormone. Take on empty stomach for best absorption.',
    requiresPrescription: true,
  ),

  'metoprolol': Medication(
    name: 'Metoprolol',
    activeIngredient: 'Metoprolol Tartrate',
    usedFor: ['High blood pressure', 'Angina', 'Heart attack', 'Arrhythmias'],
    whenToUse: ['Daily as prescribed', 'With or without food', 'Regular dosing important'],
    contraindications: ['Beta-blocker allergy', 'Severe bradycardia', 'Heart block', 'Uncontrolled asthma'],
    dosage: 'Usually 50-200mg daily in divided doses',
    sideEffects: ['Fatigue', 'Dizziness', 'Slow heart rate', 'Sexual dysfunction', 'Sleep issues'],
    simpleExplanation: 'Metoprolol slows heart rate and lowers blood pressure. Take as prescribed.',
    requiresPrescription: true,
  ),

  'amlodipine': Medication(
    name: 'Amlodipine',
    activeIngredient: 'Amlodipine Besylate',
    usedFor: ['High blood pressure', 'Chest pain (angina)', 'Coronary artery disease'],
    whenToUse: ['Daily as prescribed', 'With or without food', 'Long-term management'],
    contraindications: ['Calcium channel blocker allergy', 'Severe aortic stenosis', 'Severe hypotension'],
    dosage: 'Usually 5-10mg once daily',
    sideEffects: ['Swelling in ankles/feet', 'Headache', 'Dizziness', 'Fatigue', 'Flushing'],
    simpleExplanation: 'Amlodipine relaxes blood vessels to improve blood flow and lower pressure.',
    requiresPrescription: true,
  ),

  'albuterol': Medication(
    name: 'Albuterol (Salbutamol)',
    activeIngredient: 'Albuterol Sulfate',
    usedFor: ['Asthma', 'COPD', 'Bronchospasm', 'Exercise-induced asthma'],
    whenToUse: ['For sudden breathing trouble', 'Before exercise', 'As rescue inhaler'],
    contraindications: ['Albuterol allergy', 'Severe hypersensitivity to milk proteins (some dry powders)'],
    dosage: 'Usually 2 puffs every 4-6 hours as needed',
    sideEffects: ['Shakiness', 'Increased heart rate', 'Headache', 'Nervousness', 'Throat irritation'],
    simpleExplanation: 'Albuterol is a rescue inhaler that opens your airways quickly during asthma attacks.',
    requiresPrescription: true,
  ),

  'losartan': Medication(
    name: 'Losartan',
    activeIngredient: 'Losartan Potassium',
    usedFor: ['High blood pressure', 'Diabetic kidney disease', 'Stroke prevention'],
    whenToUse: ['Daily as prescribed', 'Usually same time each day', 'Long-term therapy'],
    contraindications: ['ARB allergy', 'Pregnancy', 'Severe liver/kidney disease', 'Concurrent Aliskiren use'],
    dosage: 'Usually 50-100mg once daily',
    sideEffects: ['Dizziness', 'Fatigue', 'Diarrhea', 'High potassium', 'Cough (less common than ACE inhibitors)'],
    simpleExplanation: 'Losartan helps lower blood pressure and protects your kidneys from diabetes damage.',
    requiresPrescription: true,
  ),

  'gabapentin': Medication(
    name: 'Gabapentin',
    activeIngredient: 'Gabapentin',
    usedFor: ['Nerve pain', 'Seizures', 'Hot flashes', 'Restless leg syndrome'],
    whenToUse: ['As prescribed', 'Multiple times daily', 'Take with or without food'],
    contraindications: ['Gabapentin allergy', 'Abrupt discontinuation'],
    dosage: 'Usually 300-600mg three times daily',
    sideEffects: ['Dizziness', 'Fatigue', 'Blurred vision', 'Weight gain', 'Mood changes'],
    simpleExplanation: 'Gabapentin helps nerve pain and seizures. Can take with food.',
    requiresPrescription: true,
  ),

  'hydrochlorothiazide': Medication(
    name: 'Hydrochlorothiazide (HCTZ)',
    activeIngredient: 'Hydrochlorothiazide',
    usedFor: ['High blood pressure', 'Swelling (edema)', 'Water retention'],
    whenToUse: ['Once daily in morning', 'To avoid waking up at night to urinate'],
    contraindications: ['Sulfa allergy (sometimes)', 'Anuria', 'Severe electrolyte imbalance'],
    dosage: 'Usually 12.5-50mg once daily',
    sideEffects: ['Increased urination', 'Dizziness', 'Lightheadedness', 'Electrolyte imbalance', 'Photosensitivity'],
    simpleExplanation: 'A "water pill" that helps your body get rid of excess salt and water through urine.',
    requiresPrescription: true,
  ),

  'sertraline': Medication(
    name: 'Sertraline',
    activeIngredient: 'Sertraline Hydrochloride',
    usedFor: ['Depression', 'Anxiety', 'OCD', 'PTSD', 'Panic disorder'],
    whenToUse: ['Once daily', 'With or without food', 'Takes 2-4 weeks for full effect'],
    contraindications: ['SSRI allergy', 'MAOI use', 'Uncontrolled narrow-angle glaucoma'],
    dosage: 'Usually 50mg daily, range 50-200mg',
    sideEffects: ['Nausea', 'Insomnia', 'Sexual dysfunction', 'Headache', 'Withdrawal if stopped abruptly'],
    simpleExplanation: 'Sertraline helps depression and anxiety. Takes time to work - be patient.',
    requiresPrescription: true,
  ),

  'furosemide': Medication(
    name: 'Furosemide (Lasix)',
    activeIngredient: 'Furosemide',
    usedFor: ['Edema (swelling)', 'Heart failure', 'Liver disease', 'Kidney disease'],
    whenToUse: ['As prescribed', 'Usually in morning', 'Follow fluid/diet advice'],
    contraindications: ['Anuria', 'Severe electrolyte depletion', 'Hypersensitivity to sulfonamides'],
    dosage: 'Usually 20-80mg per dose',
    sideEffects: ['Frequent urination', 'Dehydration', 'Low potassium', 'Dizziness', 'Muscle cramps'],
    simpleExplanation: 'Strong water pill that helps remove extra fluid from the body in conditions like heart failure.',
    requiresPrescription: true,
  ),

  'azithromycin': Medication(
    name: 'Azithromycin (Z-Pak)',
    activeIngredient: 'Azithromycin',
    usedFor: ['Bacterial infections', 'Pneumonia', 'Strep throat', 'Sinus infections'],
    whenToUse: ['Short course as prescribed', 'Usually 3-5 days', 'Complete full course'],
    contraindications: ['Macrolide allergy', 'History of cholestatic jaundice', 'Liver dysfunction'],
    dosage: 'Usually 500mg day 1, then 250mg for 4 days',
    sideEffects: ['Nausea', 'Diarrhea', 'Stomach pain', 'Headache', 'Rare heart rhythm changes'],
    simpleExplanation: 'A strong antibiotic used for various bacterial infections. Short treatment time.',
    requiresPrescription: true,
  ),

  'pantoprazole': Medication(
    name: 'Pantoprazole',
    activeIngredient: 'Pantoprazole Sodium',
    usedFor: ['GERD', 'Stomach ulcers', 'Esophagitis', 'Zollinger-Ellison syndrome'],
    whenToUse: ['Once daily before breakfast', 'Regularly as prescribed'],
    contraindications: ['PPI allergy', 'Concurrent Rilpivirine use'],
    dosage: 'Usually 40mg once daily',
    sideEffects: ['Headache', 'Diarrhea', 'Nausea', 'Stomach pain', 'Joint pain'],
    simpleExplanation: 'Reduces stomach acid to heal the esophagus and treat severe heartburn.',
    requiresPrescription: true,
  ),

  'meloxicam': Medication(
    name: 'Meloxicam',
    activeIngredient: 'Meloxicam',
    usedFor: ['Osteoarthritis', 'Rheumatoid arthritis', 'Joint pain', 'Inflammation'],
    whenToUse: ['Once daily with food', 'Long-term for arthritis', 'Consistent dosing'],
    contraindications: ['NSAID/Aspirin allergy', 'Recent bypass surgery', 'Active GI bleeding'],
    dosage: 'Usually 7.5-15mg once daily',
    sideEffects: ['Stomach upset', 'Nausea', 'Dizziness', 'Heartburn', 'Increased BP'],
    simpleExplanation: 'Treats pain and stiffness from arthritis. Take with food to protect your stomach.',
    requiresPrescription: true,
  ),

  'tramadol': Medication(
    name: 'Tramadol',
    activeIngredient: 'Tramadol Hydrochloride',
    usedFor: ['Moderate to severe pain', 'Post-surgery pain', 'Chronic pain management'],
    whenToUse: ['As prescribed for pain', 'Every 4-6 hours as needed', 'Avoid alcohol'],
    contraindications: ['Opioid allergy', 'Severe respiratory depression', 'Acute asthma', 'MAOI use'],
    dosage: '50-100mg every 4-6 hours, max 4000mg daily',
    sideEffects: ['Dizziness', 'Nausea', 'Constipation', 'Drowsiness', 'Sweating', 'Risk of addiction'],
    simpleExplanation: 'A pain reliever for more severe pain. Can cause drowsiness and should be used carefully.',
    requiresPrescription: true,
  ),

  'clopidogrel': Medication(
    name: 'Clopidogrel (Plavix)',
    activeIngredient: 'Clopidogrel Bisulfate',
    usedFor: ['Heart attack prevention', 'Stroke prevention', 'Peripheral artery disease'],
    whenToUse: ['Once daily as prescribed', 'Often used with aspirin', 'Before/after heart procedures'],
    contraindications: ['Active bleeding (ulcer, brain)', 'Severe liver disease', 'Clopidogrel allergy'],
    dosage: 'Usually 75mg once daily',
    sideEffects: ['Increased bleeding/bruising', 'Nosebleeds', 'Stomach pain', 'Rash'],
    simpleExplanation: 'Prevents blood platelets from sticking together to avoid dangerous blood clots.',
    requiresPrescription: true,
  ),

  'montelukast': Medication(
    name: 'Montelukast (Singulair)',
    activeIngredient: 'Montelukast Sodium',
    usedFor: ['Asthma prevention', 'Allergic rhinitis', 'Exercise-induced bronchoconstriction'],
    whenToUse: ['Once daily in evening', 'Regularly for prevention', 'Not for acute attacks'],
    contraindications: ['Montelukast allergy', 'Caution with mental health history'],
    dosage: '10mg once daily in evening',
    sideEffects: ['Headache', 'Upper respiratory infection', 'Stomach pain', 'Mood/behavior changes (Warning)'],
    simpleExplanation: 'Helps prevent asthma attacks and seasonal allergies. Take every evening.',
    requiresPrescription: true,
  ),

  'rosuvastatin': Medication(
    name: 'Rosuvastatin (Crestor)',
    activeIngredient: 'Rosuvastatin Calcium',
    usedFor: ['High cholesterol', 'Heart disease prevention', 'Plaque reduction'],
    whenToUse: ['Once daily', 'With or without food', 'Any time of day'],
    contraindications: ['Statin allergy', 'Active liver disease', 'Pregnancy', 'Breastfeeding'],
    dosage: 'Usually 5-40mg once daily',
    sideEffects: ['Muscle pain', 'Headache', 'Abdominal pain', 'Nausea', 'Weakness'],
    simpleExplanation: 'A potent statin that lowers "bad" cholesterol and raises "good" cholesterol.',
    requiresPrescription: true,
  ),

  'escitalopram': Medication(
    name: 'Escitalopram (Lexapro)',
    activeIngredient: 'Escitalopram Oxalate',
    usedFor: ['Depression', 'Generalized Anxiety Disorder (GAD)', 'Panic disorder'],
    whenToUse: ['Once daily in morning or evening', 'Takes 1-4 weeks to work', 'Do not stop abruptly'],
    contraindications: ['SSRI allergy', 'MAOI use', 'Pimozide use'],
    dosage: 'Usually 10-20mg once daily',
    sideEffects: ['Nausea', 'Sleepiness', 'Sweating', 'Sexual dysfunction', 'Insomnia'],
    simpleExplanation: 'Treats depression and anxiety by balancing serotonin in the brain.',
    requiresPrescription: true,
  ),

  'prednisone': Medication(
    name: 'Prednisone',
    activeIngredient: 'Prednisone',
    usedFor: ['Inflammation', 'Allergic reactions', 'Autoimmune diseases', 'Asthma'],
    whenToUse: ['As prescribed', 'With food if needed', 'Follow exact dosing schedule'],
    contraindications: ['Prednisone allergy', 'Systemic fungal infections', 'Vaccinia', 'Varicella'],
    dosage: 'Varies widely from 5mg to 60mg daily',
    sideEffects: ['Increased appetite', 'Sleep problems', 'Mood changes', 'Bone loss', 'Infection risk'],
    simpleExplanation: 'Prednisone reduces inflammation and immune responses. Follow dosing carefully.',
    requiresPrescription: true,
  ),

  'bupropion': Medication(
    name: 'Bupropion (Wellbutrin)',
    activeIngredient: 'Bupropion Hydrochloride',
    usedFor: ['Depression', 'Seasonal Affective Disorder', 'Smoking cessation'],
    whenToUse: ['Once or twice daily', 'Not late at night to avoid insomnia', 'Do not crush/chew'],
    contraindications: ['Seizure disorder', 'Anorexia/Bulimia', 'MAOI use', 'Abrupt alcohol withdrawal'],
    dosage: 'Usually 150-300mg daily (XL or SR)',
    sideEffects: ['Dry mouth', 'Sleeplessness', 'Agitation', 'Headache', 'Weight loss'],
    simpleExplanation: 'An antidepressant that can also help people quit smoking.',
    requiresPrescription: true,
  ),

  'venlafaxine': Medication(
    name: 'Venlafaxine (Effexor)',
    activeIngredient: 'Venlafaxine Hydrochloride',
    usedFor: ['Depression', 'Anxiety', 'Panic disorder', 'Social anxiety'],
    whenToUse: ['Once daily with food', 'Same time each day', 'Do not stop abruptly'],
    contraindications: ['SNRI allergy', 'MAOI use', 'Recent linezolid use'],
    dosage: 'Usually 37.5-225mg daily (Extended Release)',
    sideEffects: ['Nausea', 'Dry mouth', 'Sweating', 'Drowsiness', 'Increased blood pressure'],
    simpleExplanation: 'Treats depression and anxiety. Must be taken with food.',
    requiresPrescription: true,
  ),

  'trazodone': Medication(
    name: 'Trazodone',
    activeIngredient: 'Trazodone Hydrochloride',
    usedFor: ['Depression', 'Insomnia (off-label)', 'Anxiety'],
    whenToUse: ['Usually at bedtime for sleep', 'With food'],
    contraindications: ['Trazodone allergy', 'MAOI use', 'Recent heart attack'],
    dosage: 'Usually 50-150mg at bedtime for sleep',
    sideEffects: ['Drowsiness', 'Dizziness', 'Dry mouth', 'Blurred vision', 'Low blood pressure'],
    simpleExplanation: 'Used for depression but very commonly prescribed to help with sleep.',
    requiresPrescription: true,
  ),

  'warfarin': Medication(
    name: 'Warfarin (Coumadin)',
    activeIngredient: 'Warfarin Sodium',
    usedFor: ['Blood clots', 'Atrial fibrillation', 'Heart valve replacement'],
    whenToUse: ['Once daily', 'Regular blood tests (INR) required', 'Consistent Vitamin K diet'],
    contraindications: ['Active bleeding', 'Severe hypertension', 'Pregnancy', 'Major surgery recently'],
    dosage: 'Varies widely; adjusted based on blood tests',
    sideEffects: ['Bruising', 'Nosebleeds', 'Bleeding gums', 'Heavy periods', 'Rare serious bleeding'],
    simpleExplanation: 'A powerful blood thinner. Requires regular blood tests and careful monitoring.',
    requiresPrescription: true,
  ),

  'citalopram': Medication(
    name: 'Citalopram (Celexa)',
    activeIngredient: 'Citalopram Hydrobromide',
    usedFor: ['Depression', 'Panic disorder'],
    whenToUse: ['Once daily in morning or evening', 'Takes weeks for full effect'],
    contraindications: ['SSRI allergy', 'MAOI use', 'Long QT syndrome'],
    dosage: 'Usually 20-40mg once daily',
    sideEffects: ['Nausea', 'Dry mouth', 'Sleepiness', 'Sweating', 'Tremor'],
    simpleExplanation: 'A common SSRI antidepressant used for various mood disorders.',
    requiresPrescription: true,
  ),

  'duloxetine': Medication(
    name: 'Duloxetine (Cymbalta)',
    activeIngredient: 'Duloxetine Hydrochloride',
    usedFor: ['Depression', 'Anxiety', 'Neuropathic pain', 'Fibromyalgia', 'Chronic muscle pain'],
    whenToUse: ['Once or twice daily', 'With or without food', 'Swallow whole'],
    contraindications: ['SNRI allergy', 'MAOI use', 'Uncontrolled narrow-angle glaucoma', 'Severe liver/kidney disease'],
    dosage: 'Usually 30-60mg once daily',
    sideEffects: ['Nausea', 'Dry mouth', 'Drowsiness', 'Constipation', 'Loss of appetite'],
    simpleExplanation: 'Treats both mood and certain types of chronic physical pain.',
    requiresPrescription: true,
  ),

  'carvedilol': Medication(
    name: 'Carvedilol',
    activeIngredient: 'Carvedilol',
    usedFor: ['Heart failure', 'High blood pressure', 'Left ventricular dysfunction'],
    whenToUse: ['Twice daily with food', 'Consistent use critical'],
    contraindications: ['Asthma', 'Severe heart block', 'Severe bradycardia', 'Severe liver disease'],
    dosage: 'Usually 3.125-25mg twice daily',
    sideEffects: ['Dizziness', 'Fatigue', 'Low blood pressure', 'Weight gain', 'Diarrhea'],
    simpleExplanation: 'Helps your heart pump better and lowers blood pressure. Take with food.',
    requiresPrescription: true,
  ),

  'alprazolam': Medication(
    name: 'Alprazolam (Xanax)',
    activeIngredient: 'Alprazolam',
    usedFor: ['Anxiety disorders', 'Panic disorder'],
    whenToUse: ['As prescribed for acute anxiety', 'Short-term use usually', 'Avoid alcohol'],
    contraindications: ['Benzodiazepine allergy', 'Narrow-angle glaucoma', 'Severe respiratory insufficiency'],
    dosage: 'Usually 0.25-0.5mg three times daily',
    sideEffects: ['Drowsiness', 'Dizziness', 'Lightheadedness', 'Memory issues', 'Risk of dependence'],
    simpleExplanation: 'A fast-acting medication for severe anxiety and panic. Use only as directed.',
    requiresPrescription: true,
  ),

  'spironolactone': Medication(
    name: 'Spironolactone',
    activeIngredient: 'Spironolactone',
    usedFor: ['Heart failure', 'High blood pressure', 'Fluid retention', 'Acne (off-label)', 'PCOS'],
    whenToUse: ['Once or twice daily', 'With or without food'],
    contraindications: ['High potassium', 'Addison\'s disease', 'Severe kidney disease'],
    dosage: 'Usually 25-100mg daily',
    sideEffects: ['Increased potassium', 'Dizziness', 'Frequent urination', 'Breast tenderness', 'Headache'],
    simpleExplanation: 'A potassium-sparing water pill often used for heart and skin conditions.',
    requiresPrescription: true,
  ),

  'atenolol': Medication(
    name: 'Atenolol',
    activeIngredient: 'Atenolol',
    usedFor: ['High blood pressure', 'Angina (chest pain)', 'Heart attack prevention'],
    whenToUse: ['Once or twice daily', 'Consistent timing'],
    contraindications: ['Severe bradycardia', 'Heart block', 'Cardiogenic shock'],
    dosage: 'Usually 25-100mg once daily',
    sideEffects: ['Fatigue', 'Cold hands/feet', 'Dizziness', 'Slow heart rate', 'Depression'],
    simpleExplanation: 'A beta-blocker that slows your heart and lowers blood pressure.',
    requiresPrescription: true,
  ),

  'cyclobenzaprine': Medication(
    name: 'Cyclobenzaprine (Flexeril)',
    activeIngredient: 'Cyclobenzaprine Hydrochloride',
    usedFor: ['Muscle spasms', 'Acute musculoskeletal pain'],
    whenToUse: ['As prescribed for short-term', 'Usually at night due to drowsiness'],
    contraindications: ['Recent MI', 'Heart rhythm disorders', 'Heart failure', 'Hyperthyroidism', 'MAOI use'],
    dosage: 'Usually 5-10mg three times daily',
    sideEffects: ['Drowsiness', 'Dry mouth', 'Dizziness', 'Fatigue', 'Blurred vision'],
    simpleExplanation: 'A muscle relaxant used for short-term relief of muscle spasms.',
    requiresPrescription: true,
  ),

  'pravastatin': Medication(
    name: 'Pravastatin',
    activeIngredient: 'Pravastatin Sodium',
    usedFor: ['High cholesterol', 'Heart disease prevention', 'Stroke prevention'],
    whenToUse: ['Once daily, usually in evening'],
    contraindications: ['Statin allergy', 'Active liver disease', 'Pregnancy', 'Breastfeeding'],
    dosage: 'Usually 20-80mg once daily',
    sideEffects: ['Muscle pain', 'Cold-like symptoms', 'Headache', 'Nausea', 'Vomiting'],
    simpleExplanation: 'Lowers cholesterol and is often better tolerated than other statins.',
    requiresPrescription: true,
  ),

  'zolpidem': Medication(
    name: 'Zolpidem (Ambien)',
    activeIngredient: 'Zolpidem Tartrate',
    usedFor: ['Insomnia (difficulty falling asleep)'],
    whenToUse: ['Immediately before bed', 'Only if you can get 7-8 hours of sleep', 'Short-term'],
    contraindications: ['Complex sleep behavior history', 'Severe liver disease', 'Respiratory depression'],
    dosage: '5mg for women, 5-10mg for men at bedtime',
    sideEffects: ['Drowsiness next day', 'Dizziness', '"Sleep-driving" or other complex behaviors', 'Memory loss'],
    simpleExplanation: 'A sedative to help you fall asleep. Take only right before bed.',
    requiresPrescription: true,
  ),

  'lorazepam': Medication(
    name: 'Lorazepam (Ativan)',
    activeIngredient: 'Lorazepam',
    usedFor: ['Anxiety', 'Insomnia due to anxiety', 'Seizures', 'Pre-surgery sedation'],
    whenToUse: ['As prescribed', 'Usually short-term', 'Avoid alcohol'],
    contraindications: ['Benzodiazepine allergy', 'Narrow-angle glaucoma', 'Severe breathing problems'],
    dosage: 'Usually 2-6mg daily in divided doses',
    sideEffects: ['Drowsiness', 'Dizziness', 'Weakness', 'Unsteadiness', 'Memory problems'],
    simpleExplanation: 'Used for anxiety and seizures. Can be habit-forming if used long-term.',
    requiresPrescription: true,
  ),

  'oxycodone': Medication(
    name: 'Oxycodone',
    activeIngredient: 'Oxycodone Hydrochloride',
    usedFor: ['Severe pain', 'Cancer pain', 'Post-operative pain'],
    whenToUse: ['Strictly as prescribed', 'Avoid alcohol', 'Highly regulated'],
    contraindications: ['Opioid allergy', 'Severe asthma', 'Bowel obstruction (paralytic ileus)'],
    dosage: 'Varies; strictly controlled',
    sideEffects: ['Constipation', 'Nausea', 'Drowsiness', 'Itching', 'Respiratory depression', 'Addiction risk'],
    simpleExplanation: 'A powerful opioid pain reliever for very severe pain. High risk of addiction.',
    requiresPrescription: true,
  ),

  'allopurinol': Medication(
    name: 'Allopurinol',
    activeIngredient: 'Allopurinol',
    usedFor: ['Gout prevention', 'Kidney stones', 'High uric acid levels'],
    whenToUse: ['Once daily after meals', 'Drink plenty of water', 'Long-term prevention'],
    contraindications: ['Severe allopurinol hypersensitivity', 'HLA-B*5801 allele (high risk for rash)'],
    dosage: 'Usually 100-300mg daily',
    sideEffects: ['Skin rash (Stop immediately!)', 'Nausea', 'Drowsiness', 'Gout flare-up (initially)'],
    simpleExplanation: 'Prevents gout attacks by lowering uric acid. Stop if you get any rash.',
    requiresPrescription: true,
  ),

  'estradiol': Medication(
    name: 'Estradiol',
    activeIngredient: 'Estradiol',
    usedFor: ['Menopause symptoms', 'Estrogen deficiency', 'Osteoporosis prevention'],
    whenToUse: ['As prescribed (Pill, Patch, Gel)', 'Follow cycle if directed'],
    contraindications: ['History of breast cancer', 'History of blood clots', 'Unexplained vaginal bleeding', 'Pregnancy'],
    dosage: 'Varies by form (0.5-2mg oral)',
    sideEffects: ['Breast tenderness', 'Headache', 'Nausea', 'Weight changes', 'Mood swings'],
    simpleExplanation: 'A hormone replacement therapy for menopause symptoms and estrogen deficiency.',
    requiresPrescription: true,
  ),

  'glipizide': Medication(
    name: 'Glipizide',
    activeIngredient: 'Glipizide',
    usedFor: ['Type 2 diabetes', 'Blood sugar control'],
    whenToUse: ['30 minutes before breakfast', 'Same time each day'],
    contraindications: ['Type 1 diabetes', 'Diabetic ketoacidosis', 'Sulfa allergy (caution)'],
    dosage: 'Usually 5-20mg once daily',
    sideEffects: ['Low blood sugar (hypoglycemia)', 'Nausea', 'Dizziness', 'Weight gain'],
    simpleExplanation: 'Stimulates the pancreas to produce more insulin to lower blood sugar.',
    requiresPrescription: true,
  ),

  'clonazepam': Medication(
    name: 'Clonazepam (Klonopin)',
    activeIngredient: 'Clonazepam',
    usedFor: ['Seizures', 'Panic disorder', 'Anxiety'],
    whenToUse: ['As prescribed', 'Consistent timing', 'Do not stop abruptly'],
    contraindications: ['Benzodiazepine allergy', 'Severe liver disease', 'Glaucoma'],
    dosage: 'Usually 0.5-2mg daily',
    sideEffects: ['Drowsiness', 'Dizziness', 'Coordination problems', 'Depression', 'Fatigue'],
    simpleExplanation: 'Used for panic attacks and seizures. Long-acting benzodiazepine.',
    requiresPrescription: true,
  ),

  'loratadine': Medication(
    name: 'Loratadine',
    activeIngredient: 'Loratadine',
    usedFor: ['Allergies', 'Itching', 'Hives', 'Allergic rhinitis'],
    whenToUse: ['Once daily', 'With or without food', 'Best taken at same time'],
    contraindications: ['Loratadine allergy', 'Severe liver disease', 'Kidney disease'],
    dosage: '10mg once daily',
    sideEffects: ['Headache', 'Dry mouth', 'Fatigue', 'Nausea', 'Generally well-tolerated'],
    simpleExplanation: 'Loratadine treats allergies and itching. Non-drowsy antihistamine.',
  ),

  'cetirizine': Medication(
    name: 'Cetirizine',
    activeIngredient: 'Cetirizine Hydrochloride',
    usedFor: ['Allergies', 'Hives', 'Itching', 'Allergic reactions'],
    whenToUse: ['Once daily', 'With or without food', 'Can take in morning or evening'],
    contraindications: ['Cetirizine allergy', 'Severe kidney disease'],
    dosage: '10mg once daily',
    sideEffects: ['Drowsiness (more than loratadine)', 'Headache', 'Dry mouth', 'Fatigue'],
    simpleExplanation: 'Cetirizine relieves allergies and itching. May cause drowsiness.',
  ),

  'fluticasone': Medication(
    name: 'Fluticasone Nasal Spray',
    activeIngredient: 'Fluticasone Propionate',
    usedFor: ['Nasal allergies', 'Allergic rhinitis', 'Nasal polyps', 'Sinus inflammation'],
    whenToUse: ['Once or twice daily', 'In each nostril', 'Regular use for best effect'],
    contraindications: ['Fluticasone allergy', 'Untreated infections', 'Recent nasal surgery'],
    dosage: '1-2 sprays each nostril once or twice daily',
    sideEffects: ['Nasal irritation', 'Epistaxis', 'Sore throat', 'Headache', 'Generally well-tolerated'],
    simpleExplanation: 'Fluticasone spray reduces nasal inflammation from allergies. Use regularly.',
  ),

  'cimetidine': Medication(
    name: 'Cimetidine',
    activeIngredient: 'Cimetidine',
    usedFor: ['Heartburn', 'GERD', 'Ulcers', 'Acid reflux'],
    whenToUse: ['As needed for heartburn', 'With meals and at bedtime', 'Standard OTC dosing'],
    contraindications: ['Cimetidine allergy', 'Severe kidney/liver disease'],
    dosage: '200mg with meals and at bedtime, up to 400mg at bedtime',
    sideEffects: ['Headache', 'Constipation', 'Diarrhea', 'Nausea', 'Rare interactions'],
    simpleExplanation: 'Cimetidine reduces stomach acid and treats heartburn. Take as directed.',
  ),

  'ranitidine': Medication(
    name: 'Ranitidine',
    activeIngredient: 'Ranitidine Hydrochloride',
    usedFor: ['Heartburn', 'GERD', 'Ulcer treatment', 'Stomach acid reduction'],
    whenToUse: ['As directed', 'With or without food', 'Can take before meals or bedtime'],
    contraindications: ['Ranitidine allergy', 'Severe kidney disease', 'Porphyria'],
    dosage: '150mg twice daily or 300mg at bedtime',
    sideEffects: ['Headache', 'Constipation', 'Diarrhea', 'Nausea', 'Rare serious reactions'],
    simpleExplanation: 'Ranitidine reduces stomach acid and treats heartburn. Take as directed.',
  ),

  'naproxen': Medication(
    name: 'Naproxen (Aleve)',
    activeIngredient: 'Naproxen Sodium',
    usedFor: ['Pain relief', 'Inflammation', 'Fever', 'Arthritis', 'Menstrual cramps'],
    whenToUse: ['Every 8-12 hours with food', 'Longer lasting than ibuprofen'],
    contraindications: ['NSAID allergy', 'Active ulcers', 'Recent bypass surgery', 'Severe kidney disease'],
    dosage: '220mg every 8-12 hours, max 660mg daily (OTC)',
    sideEffects: ['Stomach upset', 'Nausea', 'Dizziness', 'Heartburn', 'Headache'],
    simpleExplanation: 'Long-lasting pain and inflammation relief. Often used for arthritis.',
  ),

  'diphenhydramine': Medication(
    name: 'Diphenhydramine (Benadryl)',
    activeIngredient: 'Diphenhydramine Hydrochloride',
    usedFor: ['Allergies', 'Sleep aid', 'Motion sickness', 'Common cold'],
    whenToUse: ['Every 4-6 hours as needed', 'At bedtime for sleep', 'Can cause significant drowsiness'],
    contraindications: ['Diphenhydramine allergy', 'Elderly (due to confusion risk)', 'Glaucoma', 'Prostate enlargement'],
    dosage: '25-50mg every 4-6 hours',
    sideEffects: ['Drowsiness', 'Dry mouth', 'Dizziness', 'Blurred vision', 'Urinary retention'],
    simpleExplanation: 'Strong antihistamine that helps allergies but causes marked drowsiness.',
  ),

  'dextromethorphan': Medication(
    name: 'Dextromethorphan',
    activeIngredient: 'Dextromethorphan Hydrobromide',
    usedFor: ['Cough suppression'],
    whenToUse: ['Every 4-12 hours as needed for dry cough'],
    contraindications: ['MAOI use', 'Product-specific sensitivities'],
    dosage: '10-30mg every 4-8 hours',
    sideEffects: ['Dizziness', 'Drowsiness', 'Nausea', 'Restlessness'],
    simpleExplanation: 'Used to temporarily relieve a non-productive (dry) cough.',
  ),

  'guaifenesin': Medication(
    name: 'Guaifenesin (Mucinex)',
    activeIngredient: 'Guaifenesin',
    usedFor: ['Chest congestion', 'Productive cough', 'Mucus thinning'],
    whenToUse: ['Every 4-12 hours with plenty of water'],
    contraindications: ['Guaifenesin allergy'],
    dosage: '200-400mg every 4 hours or 600-1200mg every 12 hours (ER)',
    sideEffects: ['Nausea', 'Vomiting', 'Stomach pain', 'Dizziness', 'Headache'],
    simpleExplanation: 'Helps loosen mucus in your lungs so you can cough it up more easily.',
  ),

  'loperamide': Medication(
    name: 'Loperamide (Imodium)',
    activeIngredient: 'Loperamide Hydrochloride',
    usedFor: ['Diarrhea relief'],
    whenToUse: ['After first loose stool', 'Avoid in case of high fever or bloody stool'],
    contraindications: ['Infectious diarrhea (caution)', 'Colitis', 'Abdominal pain without diarrhea'],
    dosage: '4mg initially, then 2mg after each loose stool, max 8-16mg daily',
    sideEffects: ['Constipation', 'Abdominal cramps', 'Dizziness', 'Nausea'],
    simpleExplanation: 'Slows down your digestive system to treat sudden diarrhea.',
  ),

  'simethicone': Medication(
    name: 'Simethicone (Gas-X)',
    activeIngredient: 'Simethicone',
    usedFor: ['Gas relief', 'Bloating', 'Abdominal pressure'],
    whenToUse: ['After meals and at bedtime as needed'],
    contraindications: ['Simethicone allergy'],
    dosage: '40-125mg four times daily as needed',
    sideEffects: ['Rarely any side effects'],
    simpleExplanation: 'Helps break up gas bubbles in the stomach and intestines.',
  ),

  'bisacodyl': Medication(
    name: 'Bisacodyl (Dulcolax)',
    activeIngredient: 'Bisacodyl',
    usedFor: ['Constipation relief', 'Bowel prep for surgery/colonoscopy'],
    whenToUse: ['Once daily, usually at night for morning bowel movement', 'Short-term only'],
    contraindications: ['Appendicitis', 'Bowel obstruction', 'Severe abdominal pain', 'Vomiting'],
    dosage: '5-15mg once daily',
    sideEffects: ['Stomach cramps', 'Diarrhea', 'Nausea', 'Electrolyte imbalance (long-term)'],
    simpleExplanation: 'A stimulant laxative that helps you have a bowel movement within 6-12 hours.',
  ),

  'famotidine': Medication(
    name: 'Famotidine (Pepcid)',
    activeIngredient: 'Famotidine',
    usedFor: ['Heartburn', 'Acid reflux', 'GERD', 'Stomach ulcers'],
    whenToUse: ['15-60 minutes before trigger food/drink or at bedtime'],
    contraindications: ['Famotidine allergy', 'Severe kidney disease'],
    dosage: '10-20mg once or twice daily',
    sideEffects: ['Headache', 'Dizziness', 'Constipation', 'Diarrhea'],
    simpleExplanation: 'An H2 blocker that reduces the amount of acid your stomach produces.',
  ),

  'psyllium': Medication(
    name: 'Psyllium (Metamucil)',
    activeIngredient: 'Psyllium Husk',
    usedFor: ['Constipation', 'Fiber supplement', 'Cholesterol lowering (mild)'],
    whenToUse: ['Mixed with at least 8oz of liquid', 'Follow with more water'],
    contraindications: ['Difficulty swallowing', 'Bowel obstruction', 'Fecal impaction'],
    dosage: '1 tablespoon/sachet mixed in liquid 1-3 times daily',
    sideEffects: ['Gas', 'Bloating', 'Abdominal cramps', 'Choking if not enough water taken'],
    simpleExplanation: 'A natural fiber supplement that helps with regularity. Must take with enough water.',
  ),

  'pseudoephedrine': Medication(
    name: 'Pseudoephedrine (Sudafed)',
    activeIngredient: 'Pseudoephedrine Hydrochloride',
    usedFor: ['Nasal congestion', 'Sinus pressure'],
    whenToUse: ['Every 4-12 hours as needed', 'Avoid close to bedtime (can be stimulating)'],
    contraindications: ['Severe hypertension', 'Severe CAD', 'MAOI use', 'Narrow-angle glaucoma'],
    dosage: '30-60mg every 4-6 hours, max 240mg daily',
    sideEffects: ['Increased heart rate', 'Nervousness', 'Insomnia', 'Dizziness', 'Increased BP'],
    simpleExplanation: 'Decongestant that narrows blood vessels in the nose to reduce swelling.',
  ),

  'docusate': Medication(
    name: 'Docusate Sodium (Colace)',
    activeIngredient: 'Docusate Sodium',
    usedFor: ['Constipation prevention', 'Stool softening'],
    whenToUse: ['Once or twice daily', 'Best if stools are hard/dry'],
    contraindications: ['Bowel obstruction', 'Nausea/Vomiting', 'Mineral oil use'],
    dosage: '50-300mg daily',
    sideEffects: ['Stomach cramps', 'Nausea', 'Throat irritation (liquid form)'],
    simpleExplanation: 'A stool softener that makes bowel movements easier and more comfortable.',
  ),

};
