import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  static const List<Locale> supportedLocales = [
    Locale('en'),
    Locale('ar'),
    Locale('fr'),
    Locale('es'),
    Locale('de'),
  ];

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'appTitle': 'AI Medicament Scanner',
      'scan': 'Scan',
      'docs': 'Docs',
      'imaging': 'Imaging',
      'trends': 'Trends',
      'search': 'Search',
      'settings': 'Settings',
      'aiAssistant': 'AI Assistant',
      'skip': 'Skip',
      'next': 'Next',
      'getStarted': 'Get Started',
      'retry': 'Retry',
      'error': 'Error',
      'loading': 'Loading...',
      'success': 'Success',
      'done': 'Done',
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'share': 'Share',
      'export': 'Export Report',
      'medicationScanner': 'Medication Scanner',
      'documentAnalysis': 'Document Analysis',
      'medicalImaging': 'Medical Imaging',
      'results': 'Results',
      'profile': 'Profile',
      'chat': 'Chat',
      'pharmacy': 'Pharmacy',
      'markTaken': 'Mark Taken',
      'taken': 'Taken',
      'setReminder': 'Set Reminder',
      'findPharmacy': 'Find Pharmacy',
      'goodMorning': 'Good Morning',
      'goodAfternoon': 'Good Afternoon',
      'goodEvening': 'Good Evening',
      'chooseFeature': 'Choose a Feature',
      'familyProfiles': 'Family Health Profiles',
      'addNew': 'Add New',
      'safetyAlerts': 'Safety Alerts Detected',
      'activeMedications': 'Active Medications',
      'noActiveMedications': 'No active medications tracked. Scan your medicines to add reminders.',
      'recentAnalyses': 'Recent Analyses',
      'viewAll': 'View All',
      'safetyReminder': 'Safety Reminder',
      'appearance': 'Appearance',
      'notifications': 'Notifications',
      'dataPrivacy': 'Data & Privacy',
      'about': 'About',
      'systemDefault': 'System Default',
      'light': 'Light',
      'dark': 'Dark',
      'exportBackup': 'Export Backup',
      'importBackup': 'Import Backup',
      'clearAllData': 'Clear All Data',
      'usageAnalytics': 'Usage Analytics',
      'appVersion': 'App Version',
      'license': 'License',
      'privacyPolicy': 'Privacy Policy',
      'quickAccess': 'Quick Access',
      'me': 'Me',
      'healthProfileActive': 'Health Profile Active',
      'setUpProfile': 'Set up your health profile',
      'consultDoctor': 'IMPORTANT: Please consult your doctor immediately regarding these combinations.',
      'signIn': 'Sign In',
      'signUp': 'Sign Up',
      'email': 'Email',
      'password': 'Password',
      'fullName': 'Full Name',
      'createAccount': 'Create Account',
      'welcomeBack': 'Welcome Back',
      'alreadyHaveAccount': 'Already have an account? Sign In',
      'dontHaveAccount': "Don't have an account? Sign Up",
      'invalidEmail': 'Please enter a valid email',
      'shortPassword': 'Password must be at least 6 characters',
      'requiredField': 'This field is required',
      'successCreateAccount': 'Account created successfully!',
      'patientName': 'Patient Name',
      'date': 'Date',
      'detailedAnalysis': 'Detailed Analysis',
      'keyFindings': 'Key Findings',
      'abnormalValues': 'Abnormal Values',
      'recommendations': 'Recommendations',
      'dosageGuidance': 'Dosage Guidance',
      'sideEffects': 'Side Effects',
      'indications': 'Indications',
      'usageInstructions': 'Usage Instructions',
      'contraindications': 'Contraindications',
      'imagingType': 'Imaging Type',
      'bodyPart': 'Body Part',
      'observations': 'Observations',
      'assessment': 'Assessment',
      'simpleExplanation': 'Simple Explanation',
      'medicalDisclaimer': 'Medical Disclaimer',
      'disclaimerText': 'This report was generated by an AI tool for informational purposes only. It is NOT a substitute for professional medical advice, diagnosis, or treatment. Always seek the advice of your physician.',
      'medicationReminders': 'Medication Reminders',
      'notificationsEnabled': 'Notifications Enabled',
      'notificationsDisabled': 'Notifications Disabled',
      'howToUse': 'How to use:',
      'howToUseDesc': '1. Take a photo or upload an image\n2. Make sure it is clear and readable\n3. Tap Analyze to get detailed information',
      'selectImage': 'Tap to select image',
      'cameraOrGallery': 'Camera or Gallery',
      'analyzing': 'Analyzing...',
      'safetyNotice': 'Results require professional interpretation. Discuss with your doctor.',
      'takePhoto': 'Take a Photo',
      'chooseGallery': 'Choose from Gallery',
      'clearImage': 'Clear Image',
      'clearDocument': 'Clear Document',
      'analyzeMedication': 'Analyze Medication',
      'analyzeDocument': 'Analyze Document',
      'analyzeImage': 'Analyze Image',
      'years': 'yrs',
      'testMarker': 'Test / Marker',
      'value': 'Value',
      'normalRange': 'Normal Range',
    },
    'ar': {
      'appTitle': 'ماسح الأدوية بالذكاء الاصطناعي',
      'scan': 'مسح',
      'docs': 'وثائق',
      'imaging': 'تصوير',
      'trends': 'اتجاهات',
      'search': 'بحث',
      'settings': 'الإعدادات',
      'aiAssistant': 'المساعد الذكي',
      'skip': 'تخطي',
      'next': 'التالي',
      'getStarted': 'ابدأ',
      'retry': 'إعادة المحاولة',
      'error': 'خطأ',
      'loading': 'جاري التحميل...',
      'success': 'نجاح',
      'done': 'تم',
      'save': 'حفظ',
      'cancel': 'إلغاء',
      'delete': 'حذف',
      'share': 'مشاركة',
      'export': 'تصدير التقرير',
      'medicationScanner': 'ماسح الأدوية',
      'documentAnalysis': 'تحليل المستندات',
      'medicalImaging': 'التصوير الطبي',
      'results': 'النتائج',
      'profile': 'الملف الشخصي',
      'chat': 'محادثة',
      'pharmacy': 'صيدلية',
      'markTaken': 'وضع علامة تناول',
      'taken': 'تم التناول',
      'setReminder': 'تعيين تذكير',
      'findPharmacy': 'البحث عن صيدلية',
      'goodMorning': 'صباح الخير',
      'goodAfternoon': 'مساء الخير',
      'goodEvening': 'مساء الخير',
      'chooseFeature': 'اختر ميزة',
      'familyProfiles': 'الملفات الصحية العائلية',
      'addNew': 'إضافة جديد',
      'safetyAlerts': 'تم اكتشاف تنبيهات أمان',
      'activeMedications': 'الأدوية النشطة',
      'noActiveMedications': 'لا توجد أدوية نشطة يتم تتبعها. قم بمسح أدويتك لإضافتها.',
      'recentAnalyses': 'التحليلات الأخيرة',
      'viewAll': 'عرض الكل',
      'safetyReminder': 'تذكير بالسلامة',
      'appearance': 'المظهر',
      'notifications': 'الإشعارات',
      'dataPrivacy': 'البيانات والخصوصية',
      'about': 'حول',
      'systemDefault': 'إعداد النظام',
      'light': 'فاتح',
      'dark': 'داكن',
      'exportBackup': 'تصدير نسخة احتياطية',
      'importBackup': 'استيراد نسخة احتياطية',
      'clearAllData': 'مسح جميع البيانات',
      'usageAnalytics': 'تحليلات الاستخدام',
      'appVersion': 'إصدار التطبيق',
      'license': 'الترخيص',
      'privacyPolicy': 'سياسة الخصوصية',
      'quickAccess': 'وصول سريع',
      'me': 'أنا',
      'healthProfileActive': 'الملف الصحي نشط',
      'setUpProfile': 'قم بإعداد ملفك الصحي',
      'consultDoctor': 'مهم: يرجى استشارة طبيبك على الفور بخصوص هذه التركيبات.',
      'signIn': 'تسجيل الدخول',
      'signUp': 'إنشاء حسـاب',
      'email': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'fullName': 'الاسم الكامل',
      'createAccount': 'إنشاء حساب',
      'welcomeBack': 'مرحباً بعودتك',
      'alreadyHaveAccount': 'لديك حساب بالفعل؟ تسجيل الدخول',
      'dontHaveAccount': 'ليس لديك حساب؟ إنشاء حساب',
      'invalidEmail': 'يرجى إدخال بريد إلكتروني صحيح',
      'shortPassword': 'يجب أن تكون كلمة المرور 6 أحرف على الأقل',
      'requiredField': 'هذا الحقل مطلوب',
      'successCreateAccount': 'تم إنشاء الحساب بنجاح!',
      'patientName': 'اسم المريض',
      'date': 'التاريخ',
      'detailedAnalysis': 'تحليل مفصل',
      'keyFindings': 'النتائج الرئيسية',
      'abnormalValues': 'القيم غير الطبيعية',
      'recommendations': 'التوصيات',
      'dosageGuidance': 'إرشادات الجرعة',
      'sideEffects': 'الآثار الجانبية',
      'indications': 'دواعي الاستعمال',
      'usageInstructions': 'تعليمات الاستخدام',
      'contraindications': 'موانع الاستعمال',
      'imagingType': 'نوع التصوير',
      'bodyPart': 'عضو الجسم',
      'observations': 'الملاحظات',
      'assessment': 'التقييم',
      'simpleExplanation': 'شرح مبسط',
      'medicalDisclaimer': 'إخلاء مسؤولية طبي',
      'disclaimerText': 'تم إنشاء هذا التقرير بواسطة أداة ذكاء اصطناعي لأغراض إعلامية فقط. إنه ليس بديلاً عن المشورة الطبية المهنية أو التشخيص أو العلاج. اطلب دائمًا مشورة طبيبك.',
      'medicationReminders': 'تذكيرات الأدوية',
      'notificationsEnabled': 'تم تفعيل الإشعارات',
      'notificationsDisabled': 'تم تعطيل الإشعارات',
      'howToUse': 'كيفية الاستخدام:',
      'howToUseDesc': '1. التقط صورة أو ارفع صورة\n2. تأكد من أنها واضحة وقابلة للقراءة\n3. اضغط على تحليل للحصول على معلومات مفصلة',
      'selectImage': 'اضغط لاختيار صورة',
      'cameraOrGallery': 'الكاميرا أو المعرض',
      'analyzing': 'جاري التحليل...',
      'safetyNotice': 'النتائج تتطلب تفسيرًا احترافيًا. ناقشها مع طبيبك.',
      'takePhoto': 'التقاط صورة',
      'chooseGallery': 'اختر من المعرض',
      'clearImage': 'مسح الصورة',
      'clearDocument': 'مسح المستند',
      'analyzeMedication': 'تحليل الدواء',
      'analyzeDocument': 'تحليل المستند',
      'analyzeImage': 'تحليل الصورة',
      'years': 'سنة',
      'testMarker': 'الاختبار / العلامة',
      'value': 'القيمة',
      'normalRange': 'المجال الطبيعي',
    },
    'fr': {
      'appTitle': 'Scanner de Médicaments IA',
      'scan': 'Scanner',
      'docs': 'Documents',
      'imaging': 'Imagerie',
      'trends': 'Tendances',
      'search': 'Rechercher',
      'settings': 'Paramètres',
      'aiAssistant': 'Assistant IA',
      'skip': 'Passer',
      'next': 'Suivant',
      'getStarted': 'Commencer',
      'retry': 'Réessayer',
      'error': 'Erreur',
      'loading': 'Chargement...',
      'success': 'Succès',
      'done': 'Terminé',
      'save': 'Enregistrer',
      'cancel': 'Annuler',
      'delete': 'Supprimer',
      'share': 'Partager',
      'export': 'Exporter le rapport',
      'medicationScanner': 'Scanner de Médicaments',
      'documentAnalysis': 'Analyse de Documents',
      'medicalImaging': 'Imagerie Médicale',
      'results': 'Résultats',
      'profile': 'Profil',
      'chat': 'Discussion',
      'pharmacy': 'Pharmacie',
      'markTaken': 'Marquer pris',
      'taken': 'Pris',
      'setReminder': 'Définir un rappel',
      'findPharmacy': 'Trouver une pharmacie',
      'goodMorning': 'Bonjour',
      'goodAfternoon': 'Bon après-midi',
      'goodEvening': 'Bonsoir',
      'chooseFeature': 'Choisir une fonction',
      'familyProfiles': 'Profils de santé familiaux',
      'addNew': 'Ajouter',
      'safetyAlerts': 'Alertes de sécurité détectées',
      'activeMedications': 'Médicaments actifs',
      'noActiveMedications': 'Aucun médicament actif suivi. Scannez vos médicaments pour les ajouter.',
      'recentAnalyses': 'Analyses récentes',
      'viewAll': 'Voir tout',
      'safetyReminder': 'Rappel de sécurité',
      'appearance': 'Apparence',
      'notifications': 'Notifications',
      'dataPrivacy': 'Données et confidentialité',
      'about': 'À propos',
      'systemDefault': 'Par défaut',
      'light': 'Clair',
      'dark': 'Sombre',
      'exportBackup': 'Exporter la sauvegarde',
      'importBackup': 'Importer la sauvegarde',
      'clearAllData': 'Effacer toutes les données',
      'usageAnalytics': 'Analyse d\'utilisation',
      'appVersion': 'Version de l\'app',
      'license': 'Licence',
      'privacyPolicy': 'Politique de confidentialité',
      'quickAccess': 'Accès rapide',
      'me': 'Moi',
      'healthProfileActive': 'Profil de santé actif',
      'setUpProfile': 'Configurez votre profil de santé',
      'consultDoctor': 'IMPORTANT : Veuillez consulter votre médecin immédiatement concernant ces combinaisons.',
      'signIn': 'Se connecter',
      'signUp': 'S\'inscrire',
      'email': 'E-mail',
      'password': 'Mot de passe',
      'fullName': 'Nom complet',
      'createAccount': 'Créer un compte',
      'welcomeBack': 'Bon retour',
      'alreadyHaveAccount': 'Vous avez déjà un compte ? Se connecter',
      'dontHaveAccount': 'Vous n\'avez pas de compte ? S\'inscrire',
      'invalidEmail': 'Veuillez saisir un e-mail valide',
      'shortPassword': 'Le mot de passe doit comporter au plus 6 caractères',
      'requiredField': 'Ce champ est obligatoire',
      'successCreateAccount': 'Compte créé avec succès !',
      'patientName': 'Nom du patient',
      'date': 'Date',
      'detailedAnalysis': 'Analyse détaillée',
      'keyFindings': 'Principales conclusions',
      'abnormalValues': 'Valeurs anormales',
      'recommendations': 'Recommandations',
      'dosageGuidance': 'Guidage posologique',
      'sideEffects': 'Effets secondaires',
      'indications': 'Indications',
      'usageInstructions': 'Instructions d\'utilisation',
      'contraindications': 'Contre-indications',
      'imagingType': 'Type d\'imagerie',
      'bodyPart': 'Partie du corps',
      'observations': 'Observations',
      'assessment': 'Évaluation',
      'simpleExplanation': 'Explication simple',
      'medicalDisclaimer': 'Avertissement médical',
      'disclaimerText': 'Ce rapport a été généré par un outil d\'IA à des fins d\'information uniquement. Il ne remplace PAS un avis médical professionnel, un diagnostic ou un traitement. Demandez toujours l\'avis de votre médecin.',
      'medicationReminders': 'Rappels de médicaments',
      'notificationsEnabled': 'Notifications activées',
      'notificationsDisabled': 'Notifications désactivées',
      'howToUse': 'Comment utiliser :',
      'howToUseDesc': '1. Prenez une photo ou téléchargez une image\n2. Assurez-vous qu\'elle soit claire et lisible\n3. Appuyez sur Analyser pour obtenir des informations détaillées',
      'selectImage': 'Appuyez pour sélectionner une image',
      'cameraOrGallery': 'Appareil photo ou Galerie',
      'analyzing': 'Analyse en cours...',
      'safetyNotice': 'Les résultats nécessitent une interprétation professionnelle. Parlez-en à votre médecin.',
      'takePhoto': 'Prendre une photo',
      'chooseGallery': 'Choisir dans la galerie',
      'clearImage': 'Effacer l\'image',
      'clearDocument': 'Effacer le document',
      'analyzeMedication': 'Analyser le médicament',
      'analyzeDocument': 'Analyser le document',
      'analyzeImage': 'Analyser l\'image',
      'years': 'ans',
      'testMarker': 'Test / Marqueur',
      'value': 'Valeur',
      'normalRange': 'Plage normale',
    },
    'es': {
      'appTitle': 'Escáner de Medicamentos IA',
      'scan': 'Escanear',
      'docs': 'Docs',
      'imaging': 'Imágenes',
      'trends': 'Tendencias',
      'search': 'Buscar',
      'settings': 'Ajustes',
      'aiAssistant': 'Asistente IA',
      'skip': 'Omitir',
      'next': 'Siguiente',
      'getStarted': 'Comenzar',
      'retry': 'Reintentar',
      'error': 'Error',
      'loading': 'Cargando...',
      'success': 'Éxito',
      'done': 'Listo',
      'save': 'Guardar',
      'cancel': 'Cancelar',
      'delete': 'Eliminar',
      'share': 'Compartir',
      'export': 'Exportar Informe',
      'medicationScanner': 'Escáner de Medicamentos',
      'documentAnalysis': 'Análisis de Documentos',
      'medicalImaging': 'Imagenología Médica',
      'results': 'Resultados',
      'profile': 'Perfil',
      'chat': 'Chat',
      'pharmacy': 'Farmacia',
      'markTaken': 'Marcar como Tomado',
      'taken': 'Tomado',
      'setReminder': 'Establecer Recordatorio',
      'findPharmacy': 'Buscar Farmacia',
      'goodMorning': 'Buenos Días',
      'goodAfternoon': 'Buenas Tardes',
      'goodEvening': 'Buenas Noches',
      'chooseFeature': 'Elige una Función',
      'familyProfiles': 'Perfiles de Salud Familiar',
      'addNew': 'Añadir Nuevo',
      'safetyAlerts': 'Alertas de Seguridad Detectadas',
      'activeMedications': 'Medicamentos Activos',
      'noActiveMedications': 'No se rastrean medicamentos activos. Escanea tus medicinas para añadir recordatorios.',
      'recentAnalyses': 'Análisis Recientes',
      'viewAll': 'Ver Todo',
      'safetyReminder': 'Recordatorio de Seguridad',
      'appearance': 'Apariencia',
      'notifications': 'Notificaciones',
      'dataPrivacy': 'Datos y Privacidad',
      'about': 'Acerca de',
      'systemDefault': 'Predeterminado del Sistema',
      'light': 'Claro',
      'dark': 'Oscuro',
      'exportBackup': 'Exportar Copia de Seguridad',
      'importBackup': 'Importar Copia de Seguridad',
      'clearAllData': 'Borrar Todos los Datos',
      'usageAnalytics': 'Analítica de Uso',
      'appVersion': 'Versión de la Aplicación',
      'license': 'Licencia',
      'privacyPolicy': 'Política de Privacidad',
      'quickAccess': 'Acceso Rápido',
      'me': 'Yo',
      'healthProfileActive': 'Perfil de Salud Activo',
      'setUpProfile': 'Configure su perfil de salud',
      'consultDoctor': 'IMPORTANTE: Consulte a su médico de inmediato sobre estas combinaciones.',
      'signIn': 'Iniciar Sesión',
      'signUp': 'Registrarse',
      'email': 'Correo Electrónico',
      'password': 'Contraseña',
      'fullName': 'Nombre Completo',
      'createAccount': 'Crear Cuenta',
      'welcomeBack': 'Bienvenido de Nuevo',
      'alreadyHaveAccount': '¿Ya tienes cuenta? Inicia sesión',
      'dontHaveAccount': '¿No tienes cuenta? Regístrate',
      'invalidEmail': 'Ingrese un correo válido',
      'shortPassword': 'La contraseña debe tener al menos 6 caracteres',
      'requiredField': 'Este campo es obligatorio',
      'successCreateAccount': '¡Cuenta creada con éxito!',
      'patientName': 'Nombre del paciente',
      'date': 'Fecha',
      'detailedAnalysis': 'Análisis detallado',
      'keyFindings': 'Hallazgos clave',
      'abnormalValues': 'Valores anormales',
      'recommendations': 'Recomendaciones',
      'dosageGuidance': 'Guía de dosificación',
      'sideEffects': 'Efectos secundarios',
      'indications': 'Indicaciones',
      'usageInstructions': 'Instrucciones de uso',
      'contraindications': 'Contraindicaciones',
      'imagingType': 'Tipo de imagen',
      'bodyPart': 'Parte del cuerpo',
      'observations': 'Observaciones',
      'assessment': 'Evaluación',
      'simpleExplanation': 'Explicación sencilla',
      'medicalDisclaimer': 'Aviso médico',
      'disclaimerText': 'Este informe fue generado por una herramienta de IA solo con fines informativos. NO sustituye el consejo médico profesional, el diagnóstico o el tratamiento. Busque siempre el consejo de su médico.',
      'medicationReminders': 'Recordatorios de Medicamentos',
      'notificationsEnabled': 'Notificaciones Activadas',
      'notificationsDisabled': 'Notificaciones Desactivadas',
      'howToUse': 'Cómo usar:',
      'howToUseDesc': '1. Tome una foto o suba una imagen\n2. Asegúrese de que sea clara y legible\n3. Toque Analizar para obtener información detallada',
      'selectImage': 'Toque para seleccionar imagen',
      'cameraOrGallery': 'Cámara o Galería',
      'analyzing': 'Analizando...',
      'safetyNotice': 'Los resultados requieren interpretación profesional. Consulte a su médico.',
      'takePhoto': 'Tomar una foto',
      'chooseGallery': 'Elegir de la galería',
      'clearImage': 'Limpiar imagen',
      'clearDocument': 'Limpiar documento',
      'analyzeMedication': 'Analizar medicamento',
      'analyzeDocument': 'Analizar documento',
      'analyzeImage': 'Analizar imagen',
      'years': 'años',
      'testMarker': 'Prueba / Marcador',
      'value': 'Valor',
      'normalRange': 'Rango normal',
    },
    'de': {
      'appTitle': 'AI Medikamenten-Scanner',
      'scan': 'Scannen',
      'docs': 'Dokumente',
      'imaging': 'Bildgebung',
      'trends': 'Trends',
      'search': 'Suchen',
      'settings': 'Einstellungen',
      'aiAssistant': 'KI-Assistent',
      'skip': 'Überspringen',
      'next': 'Weiter',
      'getStarted': 'Loslegen',
      'retry': 'Wiederholen',
      'error': 'Fehler',
      'loading': 'Laden...',
      'success': 'Erfolg',
      'done': 'Fertig',
      'save': 'Speichern',
      'cancel': 'Abbrechen',
      'delete': 'Löschen',
      'share': 'Teilen',
      'export': 'Bericht Exportieren',
      'medicationScanner': 'Medikamenten-Scanner',
      'documentAnalysis': 'Dokumentenanalyse',
      'medicalImaging': 'Medizinische Bildgebung',
      'results': 'Ergebnisse',
      'profile': 'Profil',
      'chat': 'Chat',
      'pharmacy': 'Apotheke',
      'markTaken': 'Als eingenommen markieren',
      'taken': 'Eingenommen',
      'setReminder': 'Erinnerung einstellen',
      'findPharmacy': 'Apotheke finden',
      'goodMorning': 'Guten Morgen',
      'goodAfternoon': 'Guten Tag',
      'goodEvening': 'Guten Abend',
      'chooseFeature': 'Funktion wählen',
      'familyProfiles': 'Familien-Gesundheitsprofile',
      'addNew': 'Neu hinzufügen',
      'safetyAlerts': 'Sicherheitswarnungen erkannt',
      'activeMedications': 'Aktive Medikamente',
      'noActiveMedications': 'Keine aktiven Medikamente verfolgt. Scannen Sie Ihre Medikamente, um Erinnerungen hinzuzufügen.',
      'recentAnalyses': 'Letzte Analysen',
      'viewAll': 'Alle anzeigen',
      'safetyReminder': 'Sicherheitshinweis',
      'appearance': 'Erscheinungsbild',
      'notifications': 'Benachrichtigungen',
      'dataPrivacy': 'Daten & Datenschutz',
      'about': 'Über',
      'systemDefault': 'Systemstandard',
      'light': 'Hell',
      'dark': 'Dunkel',
      'exportBackup': 'Backup exportieren',
      'importBackup': 'Backup importieren',
      'clearAllData': 'Alle Daten löschen',
      'usageAnalytics': 'Nutzungsstatistiken',
      'appVersion': 'App-Version',
      'license': 'Lizenz',
      'privacyPolicy': 'Datenschutzerklärung',
      'quickAccess': 'Schnellzugriff',
      'me': 'Ich',
      'healthProfileActive': 'Gesundheitsprofil aktiv',
      'setUpProfile': 'Richten Sie Ihr Gesundheitsprofil ein',
      'consultDoctor': 'WICHTIG: Bitte konsultieren Sie umgehend Ihren Arzt bezüglich dieser Kombinationen.',
      'signIn': 'Anmelden',
      'signUp': 'Registrieren',
      'email': 'E-Mail',
      'password': 'Passwort',
      'fullName': 'Vollständiger Name',
      'createAccount': 'Konto erstellen',
      'welcomeBack': 'Willkommen zurück',
      'alreadyHaveAccount': 'Bereits ein Konto? Anmelden',
      'dontHaveAccount': 'Noch kein Konto? Registrieren',
      'invalidEmail': 'Bitte geben Sie eine gültige E-Mail ein',
      'shortPassword': 'Passwort muss mindestens 6 Zeichen lang sein',
      'requiredField': 'Dieses Feld ist erforderlich',
      'successCreateAccount': 'Konto erfolgreich erstellt!',
      'patientName': 'Patientenname',
      'date': 'Datum',
      'detailedAnalysis': 'Detaillierte Analyse',
      'keyFindings': 'Wichtigste Befunde',
      'abnormalValues': 'Anormale Werte',
      'recommendations': 'Empfehlungen',
      'dosageGuidance': 'Dosierungshinweise',
      'sideEffects': 'Nebenwirkungen',
      'indications': 'Indikationen',
      'usageInstructions': 'Gebrauchsanweisung',
      'contraindications': 'Kontraindikationen',
      'imagingType': 'Bildgebungstyp',
      'bodyPart': 'Körperteil',
      'observations': 'Beobachtungen',
      'assessment': 'Beurteilung',
      'simpleExplanation': 'Einfache Erklärung',
      'medicalDisclaimer': 'Medizinischer Haftungsausschluss',
      'disclaimerText': 'Dieser Bericht wurde von einem KI-Tool nur zu Informationszwecken erstellt. Er ist KEIN Ersatz für professionelle medizinische Beratung, Diagnose oder Behandlung. Holen Sie immer den Rat Ihres Arztes ein.',
      'medicationReminders': 'Medikamentenerinnerungen',
      'notificationsEnabled': 'Benachrichtigungen Aktiviert',
      'notificationsDisabled': 'Benachrichtigungen Deaktiviert',
      'howToUse': 'Anwendung:',
      'howToUseDesc': '1. Foto machen oder Bild hochladen\n2. Stellen Sie sicher, dass es klar und lesbar ist\n3. Tippen Sie auf Analysieren für Details',
      'selectImage': 'Tippen zum Bild auswählen',
      'cameraOrGallery': 'Kamera oder Galerie',
      'analyzing': 'Analysiere...',
      'safetyNotice': 'Die Ergebnisse erfordern eine professionelle Interpretation. Sprechen Sie mit Ihrem Arzt.',
      'takePhoto': 'Foto machen',
      'chooseGallery': 'Aus Galerie wählen',
      'clearImage': 'Bild löschen',
      'clearDocument': 'Dokument löschen',
      'analyzeMedication': 'Medikament analysieren',
      'analyzeDocument': 'Dokument analysieren',
      'analyzeImage': 'Bild analysieren',
      'years': 'Jahre',
      'testMarker': 'Test / Marker',
      'value': 'Wert',
      'normalRange': 'Normalbereich',
    },
  };

  String translate(String key) {
    final langMap = _localizedValues[locale.languageCode];
    return langMap?[key] ?? _localizedValues['en']?[key] ?? key;
  }

  String get appTitle => translate('appTitle');
  String get scan => translate('scan');
  String get docs => translate('docs');
  String get imaging => translate('imaging');
  String get trends => translate('trends');
  String get search => translate('search');
  String get settings => translate('settings');
  String get aiAssistant => translate('aiAssistant');
  String get skip => translate('skip');
  String get next => translate('next');
  String get getStarted => translate('getStarted');
  String get retry => translate('retry');
  String get error => translate('error');
  String get loading => translate('loading');
  String get success => translate('success');
  String get done => translate('done');
  String get save => translate('save');
  String get cancel => translate('cancel');
  String get delete => translate('delete');
  String get share => translate('share');
  String get export => translate('export');
  String get medicationScanner => translate('medicationScanner');
  String get documentAnalysis => translate('documentAnalysis');
  String get medicalImaging => translate('medicalImaging');
  String get signIn => translate('signIn');
  String get signUp => translate('signUp');
  String get email => translate('email');
  String get password => translate('password');
  String get fullName => translate('fullName');
  String get createAccount => translate('createAccount');
  String get welcomeBack => translate('welcomeBack');
  String get alreadyHaveAccount => translate('alreadyHaveAccount');
  String get dontHaveAccount => translate('dontHaveAccount');
  String get invalidEmail => translate('invalidEmail');
  String get shortPassword => translate('shortPassword');
  String get requiredField => translate('requiredField');
  String get successCreateAccount => translate('successCreateAccount');
  String get results => translate('results');
  String get profile => translate('profile');
  String get chat => translate('chat');
  String get pharmacy => translate('pharmacy');
  String get markTaken => translate('markTaken');
  String get taken => translate('taken');
  String get setReminder => translate('setReminder');
  String get goodMorning => translate('goodMorning');
  String get goodAfternoon => translate('goodAfternoon');
  String get goodEvening => translate('goodEvening');
  String get findPharmacy => translate('findPharmacy');
  String get familyProfiles => translate('familyProfiles');
  String get addNew => translate('addNew');
  String get safetyAlerts => translate('safetyAlerts');
  String get activeMedications => translate('activeMedications');
  String get noActiveMedications => translate('noActiveMedications');
  String get recentAnalyses => translate('recentAnalyses');
  String get viewAll => translate('viewAll');
  String get safetyReminder => translate('safetyReminder');
  String get quickAccess => translate('quickAccess');
  String get appearance => translate('appearance');
  String get notifications => translate('notifications');
  String get dataPrivacy => translate('dataPrivacy');
  String get about => translate('about');
  String get exportBackup => translate('exportBackup');
  String get importBackup => translate('importBackup');
  String get clearAllData => translate('clearAllData');
  String get usageAnalytics => translate('usageAnalytics');
  String get appVersion => translate('appVersion');
  String get license => translate('license');
  String get privacyPolicy => translate('privacyPolicy');
  String get healthProfileActive => translate('healthProfileActive');
  String get setUpProfile => translate('setUpProfile');
  String get medicationReminders => translate('medicationReminders');
  String get notificationsEnabled => translate('notificationsEnabled');
  String get notificationsDisabled => translate('notificationsDisabled');
  String get me => translate('me');
  String get consultDoctor => translate('consultDoctor');
  String get patientName => translate('patientName');
  String get date => translate('date');
  String get detailedAnalysis => translate('detailedAnalysis');
  String get keyFindings => translate('keyFindings');
  String get abnormalValues => translate('abnormalValues');
  String get recommendations => translate('recommendations');
  String get dosageGuidance => translate('dosageGuidance');
  String get sideEffects => translate('sideEffects');
  String get indications => translate('indications');
  String get usageInstructions => translate('usageInstructions');
  String get contraindications => translate('contraindications');
  String get imagingType => translate('imagingType');
  String get bodyPart => translate('bodyPart');
  String get observations => translate('observations');
  String get assessment => translate('assessment');
  String get simpleExplanation => translate('simpleExplanation');
  String get medicalDisclaimer => translate('medicalDisclaimer');
  String get disclaimerText => translate('disclaimerText');
  String get howToUse => translate('howToUse');
  String get howToUseDesc => translate('howToUseDesc');
  String get selectImage => translate('selectImage');
  String get cameraOrGallery => translate('cameraOrGallery');
  String get analyzing => translate('analyzing');
  String get safetyNotice => translate('safetyNotice');
  String get takePhoto => translate('takePhoto');
  String get chooseGallery => translate('chooseGallery');
  String get clearImage => translate('clearImage');
  String get clearDocument => translate('clearDocument');
  String get analyzeMedication => translate('analyzeMedication');
  String get analyzeDocument => translate('analyzeDocument');
  String get analyzeImage => translate('analyzeImage');
  String get years => translate('years');
  String get testMarker => translate('testMarker');
  String get value => translate('value');
  String get normalRange => translate('normalRange');
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return ['en', 'ar', 'fr', 'es', 'de'].contains(locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}
